### ISSUE TITLE
[BUG] [ws-import-spdx] Wrong error message when apiKey is not matched to the Mend instance

### ISSUE THREAD

**Issue by tabac-mend** [whitesource-ps/ws-import-spdx#11]
**Bug Description**  
When providing a wrong APIKEY to the Mend instance , the following log is shown
`root@4220c1dfd6b3:~# ws_import_spdx -u USERKEY -k APIKEY -p SPDX_Import -pr PRODUCTKEY -o . -sbom test_spdx.json
INFO 2022-11-17 20:09:59,993 139829477881664 import_spdx: Started creation upload request
INFO 2022-11-17 20:09:59,994 139829477881664 import_spdx: Uploading data to Mend
ERROR 2022-11-17 20:10:00,269 139829477881664 import_spdx: Error during upload data to Mend: Illegal arguments
INFO 2022-11-17 20:10:00,269 139829477881664 import_spdx: Upload data finished successfully
INFO 2022-11-17 20:10:00,270 139829477881664 import_spdx: Upload request created successfully [./Mend_upload_20221117.json]`
However, the only issue is that I forgot to provide the _-a MEND_INSTANCE_URL_ .

**Steps to Reproduce**  
1. Have an account other than saas.whitesourcesoftware.com .
2. Use the following command:
`ws_import_spdx -u USERKEY -k APIKEY -p SPDX_Import -pr PRODUCTKEY -o . -sbom test_spdx.json`
3. See error message:
**ERROR 2022-11-17 20:10:00,269 139829477881664 import_spdx: Error during upload data to Mend: Illegal arguments**

**Expected Behavior**  
The log should state the apiKey doesn't match or provide an "Invalid org token" message similar to Unified Agent.

**Environment Details**  
 - OS: Ubuntu 20.04 container
 - Version: ws-import-spdx==22.11.15.1

**Comment by DimarrWS** [comment]
Created https://whitesource.atlassian.net/browse/PSD-211  ticket.

**Comment by DimarrWS** [comment]
Hi @tabac-mend ! Please, take a new release (version 22.11.24.1).

**Comment by tabac-mend** [comment]
Awesome @DimarrWS , thank you for the swift response.
The log does show now:
`Impossible to load. Illegal arguments (Bad org token)`
which is easier to understand.
